
name: MSC Devops Project for CA1
env:
  AZURE_WEBAPP_PUBLISH: bpcheck
  AZURE_WEBAPP_PACKAGE_PATH: 'publish' 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest  

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build 
      run: dotnet build --configuration Release
    - name: Execute unit tests
      run: dotnet test --no-restore --collect "Code coverage" -l:trx 
    - name: Publish Unit Test Results
      uses: dorny/test-reporter@v1
      with:
        artifact: ''
        name: MS Tests                  
        path: '**.trx'
        reporter: 'dotnet-trx' 
    - name: Publish
      run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
# Deploy to Azure Web apps
    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}               
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
